controller_list:
  - name: fake_robocol_arm_controller
    joints:
      - robocol_joint1
      - robocol_joint2
      - robocol_joint3
      - robocol_joint4
      - robocol_joint5
      - robocol_joint6
  - name: fake_hand_controller
    joints:
      - robocol_finger_joint1
      - robocol_finger_joint2
initial:
  - group: robocol_arm_hand
    pose: ready
